### PR TITLE
TypeScript Implementation

### PR DESCRIPTION
**Pull request by alqamabinsadiq**
Create Tabs component and implemented it.

### CODE REVIEW

**Comment by alqamabinsadiq** [comment]
### Before:
Screenshot 2021-06-11 at 9 53 28 PM

### After:
Screenshot 2021-06-11 at 9 53 11 PM

**Comment by UnniKrishnaPanicker** [comment]
Component files are tsx now. found 'any' type in component proptypes.
Is there any reason for giving any types for all component..?

**Comment by alqamabinsadiq** [comment]
`types` are not properly defined in the SLDS library. What I can do is this:

```
type CustomDataTableCellProps = {
    children?: any;
    item: object;
    render: (text: string, row: object) => JSX.Element;
    property: string;
};

const CustomDataTableCell = ({
    children,
    item,
    render,
    ...props
}: CustomDataTableCellProps) => (
    <DataTableCell {...props}>{render(children, item)}</DataTableCell>
);
```

In this way, we can assign the types to our custom props that we are missing or the ones that are correct in the SLDS. Let me know what you think and then I will update the PR accordingly.

**Comment by alqamabinsadiq** [comment]
Let me know if I am allowed to make these type of changes. According to our initial discussion I was being told to just replace the components and use SLDS. What I did in the above comment will be good, and will be useful for you guys too.

**Comment by UnniKrishnaPanicker** [comment]
If SLDS is not providing proper type support, you can continue like by defining types for known props. Just like you suggested above.

**Comment by alqamabinsadiq** [comment]
Please check now. I updated the PR. I used types from SLDS and added fixes within that.

**Comment by UnniKrishnaPanicker** [comment]
We have gone through the latest commits.

**Comment by alqamabinsadiq** [comment]
@UnniKrishnaPanicker Can you please share your comments?

**Comment by UnniKrishnaPanicker** [comment]
It is fine. We have merged to the master.
Thanks.

**Pull request merged**
